In [ ]:
libraries:-they are collection of modules and functions to perform specific tasks.

pandas:-data manipulation
numpy(numerical python): multi-dimensional arrays and mathematical operations

matplotlib,seaborn,plotly:data visualisation 
statistics:
sklearn(scikit learn):machine learning
keras:deep learning
tensorflow:google
pytorch:facebook

In [2]:
#pandas is used for data manipulation and we can craete series data and datafarames data using pandas

series:-contains 1d data
dataframe:-contains 2D data

SyntaxError: invalid decimal literal (3542314188.py, line 3)

In [21]:
import pandas as pd
pd.Series([1,3,5,6,7])

0    1
1    3
2    5
3    6
4    7
dtype: int64

In [22]:
#3 emp id name email salerty
dict1={"id":[111,112,113],"name":['s','p','k'],"email":['a1@gmail.com','b1@gmail.com','a1@gmail.com'],"salery":['10000','100','4500']}
dict1

{'id': [111, 112, 113],
 'name': ['s', 'p', 'k'],
 'email': ['a1@gmail.com', 'b1@gmail.com', 'a1@gmail.com'],
 'salery': ['10000', '100', '4500']}

In [23]:
pd.DataFrame(dict1)

    id name         email salery
0  111    s  a1@gmail.com  10000
1  112    p  b1@gmail.com    100
2  113    k  a1@gmail.com   4500

In [24]:

d1=pd.read_excel("C:\\Users\\ar543\\Downloads\\emp_data.xlsx")
d1

   eid ename   sal  dept
0    1    aa  1234    10
1    2    bb  2345    20
2    3    cc  3214    30
3    4    dd  5332    40

In [25]:
d2=pd.read_csv("C:\\Users\\ar543\\Downloads\\studata.txt")
d2

   sid    sname            emialid address  phoneno
0    1    priya    priya@gmail.com     dvg     9876
1    2  karthik  karthik@gmail.com     blr    12345
2    3    karan                NaN     msr    34567

In [26]:
d3=pd.read_csv("C:\\Users\\ar543\\Downloads\\mtcars.csv")
d3

,manufacturer,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
5,Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1
6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
10,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4
11,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3
12,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3
13,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3
14,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
15,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4
16,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
17,Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1
18,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
19,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
20,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1
21,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2
22,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2
23,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
24,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2
25,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1
26,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2

In [27]:
d4=pd.read_table("C:\\Users\\ar543\\Downloads\\chipotle.tsv")
d4

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

In [28]:
d5=pd.read_csv("C:\\Users\\ar543\\Downloads\\chipotle.tsv",sep="\t")
d5

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

In [29]:
d5.head(5)

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98

In [30]:
d5.tail(10)

,order_id,quantity,item_name,choice_description,item_price
4612,1831,1,Carnitas Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$9.25
4613,1831,1,Chips,NaN,$2.15
4614,1831,1,Bottled Water,NaN,$1.50
4615,1832,1,Chicken Soft Tacos,"[Fresh Tomato Salsa, [Rice, Cheese, Sour Cream]]",$8.75
4616,1832,1,Chips and Guacamole,NaN,$4.45
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

In [31]:
#make data with 500 rows
temp=d5.sample(500,)
temp

,order_id,quantity,item_name,choice_description,item_price
204,91,1,Chicken Burrito,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$8.49
3670,1469,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Pinto Beans, Chees...",$9.25
4596,1826,1,Chips and Guacamole,NaN,$4.45
4262,1700,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",$11.75
4463,1778,1,Canned Soft Drink,[Lemonade],$1.25
...,...,...,...,...,...
4506,1792,1,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Cheese, Sour Cream...",$11.25
3433,1379,1,Steak Burrito,"[[Fresh Tomato Salsa (Mild), Tomatillo-Red Chi...",$8.99
3830,1535,1,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Pinto Beans, Sour ...",$8.75
3367,1351,1,Veggie Burrito,"[[Fresh Tomato Salsa (Mild), Roasted Chili Cor...",$8.49
2974,1182,1,Steak Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Rice, Black...",$8.99

In [32]:
d5.shape

(4622, 5)

In [33]:
#how to extract only rows
d5.shape[1]

5

In [34]:
#columns names
d5.columns

Index(['order_id', 'quantity', 'item_name', 'choice_description',
       'item_price'],
      dtype='object')

In [35]:
d5.dtypes

order_id               int64
quantity               int64
item_name             object
choice_description    object
item_price            object
dtype: object

In [36]:
d3.manufacturer

0               Mazda RX4
1           Mazda RX4 Wag
2              Datsun 710
3          Hornet 4 Drive
4       Hornet Sportabout
5                 Valiant
6              Duster 360
7               Merc 240D
8                Merc 230
9                Merc 280
10              Merc 280C
11             Merc 450SE
12             Merc 450SL
13            Merc 450SLC
14     Cadillac Fleetwood
15    Lincoln Continental
16      Chrysler Imperial
17               Fiat 128
18            Honda Civic
19         Toyota Corolla
20          Toyota Corona
21       Dodge Challenger
22            AMC Javelin
23             Camaro Z28
24       Pontiac Firebird
25              Fiat X1-9
26          Porsche 914-2
27           Lotus Europa
28         Ford Pantera L
29           Ferrari Dino
30          Maserati Bora
31             Volvo 142E
Name: manufacturer, dtype: object

In [37]:
d3=pd.read_csv("C:\\Users\\ar543\\Downloads\\mtcars.csv")

In [38]:
d3

,manufacturer,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
5,Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1
6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
10,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4
11,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3
12,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3
13,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3
14,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
15,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4
16,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
17,Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1
18,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
19,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
20,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1
21,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2
22,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2
23,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
24,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2
25,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1
26,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2

In [39]:
d3.manufacturer

0               Mazda RX4
1           Mazda RX4 Wag
2              Datsun 710
3          Hornet 4 Drive
4       Hornet Sportabout
5                 Valiant
6              Duster 360
7               Merc 240D
8                Merc 230
9                Merc 280
10              Merc 280C
11             Merc 450SE
12             Merc 450SL
13            Merc 450SLC
14     Cadillac Fleetwood
15    Lincoln Continental
16      Chrysler Imperial
17               Fiat 128
18            Honda Civic
19         Toyota Corolla
20          Toyota Corona
21       Dodge Challenger
22            AMC Javelin
23             Camaro Z28
24       Pontiac Firebird
25              Fiat X1-9
26          Porsche 914-2
27           Lotus Europa
28         Ford Pantera L
29           Ferrari Dino
30          Maserati Bora
31             Volvo 142E
Name: manufacturer, dtype: object

In [40]:
d3['manufacturer']

0               Mazda RX4
1           Mazda RX4 Wag
2              Datsun 710
3          Hornet 4 Drive
4       Hornet Sportabout
5                 Valiant
6              Duster 360
7               Merc 240D
8                Merc 230
9                Merc 280
10              Merc 280C
11             Merc 450SE
12             Merc 450SL
13            Merc 450SLC
14     Cadillac Fleetwood
15    Lincoln Continental
16      Chrysler Imperial
17               Fiat 128
18            Honda Civic
19         Toyota Corolla
20          Toyota Corona
21       Dodge Challenger
22            AMC Javelin
23             Camaro Z28
24       Pontiac Firebird
25              Fiat X1-9
26          Porsche 914-2
27           Lotus Europa
28         Ford Pantera L
29           Ferrari Dino
30          Maserati Bora
31             Volvo 142E
Name: manufacturer, dtype: object

In [41]:
d3[['manufacturer']]

           manufacturer
0             Mazda RX4
1         Mazda RX4 Wag
2            Datsun 710
3        Hornet 4 Drive
4     Hornet Sportabout
5               Valiant
6            Duster 360
7             Merc 240D
8              Merc 230
9              Merc 280
10            Merc 280C
11           Merc 450SE
12           Merc 450SL
13          Merc 450SLC
14   Cadillac Fleetwood
15  Lincoln Continental
16    Chrysler Imperial
17             Fiat 128
18          Honda Civic
19       Toyota Corolla
20        Toyota Corona
21     Dodge Challenger
22          AMC Javelin
23           Camaro Z28
24     Pontiac Firebird
25            Fiat X1-9
26        Porsche 914-2
27         Lotus Europa
28       Ford Pantera L
29         Ferrari Dino
30        Maserati Bora
31           Volvo 142E

In [42]:
temp1=d3[['mpg','wt','vs','am']]
temp1

     mpg     wt  vs  am
0   21.0  2.620   0   1
1   21.0  2.875   0   1
2   22.8  2.320   1   1
3   21.4  3.215   1   0
4   18.7  3.440   0   0
5   18.1  3.460   1   0
6   14.3  3.570   0   0
7   24.4  3.190   1   0
8   22.8  3.150   1   0
9   19.2  3.440   1   0
10  17.8  3.440   1   0
11  16.4  4.070   0   0
12  17.3  3.730   0   0
13  15.2  3.780   0   0
14  10.4  5.250   0   0
15  10.4  5.424   0   0
16  14.7  5.345   0   0
17  32.4  2.200   1   1
18  30.4  1.615   1   1
19  33.9  1.835   1   1
20  21.5  2.465   1   0
21  15.5  3.520   0   0
22  15.2  3.435   0   0
23  13.3  3.840   0   0
24  19.2  3.845   0   0
25  27.3  1.935   1   1
26  26.0  2.140   0   1
27  30.4  1.513   1   1
28  15.8  3.170   0   1
29  19.7  2.770   0   1
30  15.0  3.570   0   1
31  21.4  2.780   1   1

In [43]:
rename column wt by weight and manufacturer as menu

SyntaxError: invalid syntax (1810582877.py, line 1)

In [44]:
d3.rename({"wt":"weight","manufacturer":"manu"},errors="raise",axis=1,inplace=True)

In [45]:
d3

,manu,mpg,cyl,disp,hp,drat,weight,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
5,Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1
6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
10,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4
11,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3
12,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3
13,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3
14,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
15,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4
16,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
17,Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1
18,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
19,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
20,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1
21,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2
22,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2
23,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
24,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2
25,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1
26,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2

In [46]:
#count how many unique values are in cyl column

d3['cyl'].nunique()

3

In [47]:
d3['cyl'].unique()

array([6, 4, 8])

In [48]:
d3.nunique()

manu      32
mpg       25
cyl        3
disp      27
hp        22
drat      22
weight    29
qsec      30
vs         2
am         2
gear       3
carb       6
dtype: int64

In [49]:
!git add .

warning: in the working copy of '.ipynb_checkpoints/libraries-checkpoint.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'libraries.ipynb', LF will be replaced by CRLF the next time Git touches it

In [50]:
!git commit -m "pandas libraries"

[main dfce221] pandas libraries
 2 files changed, 11612 insertions(+), 460 deletions(-)

In [51]:
!git push

To https://github.com/aryanra419/Python-class-notes
   cc95373..dfce221  main -> main

In [52]:
#create half qsec
d3["Half qsec"] = d3["qsec"]/2

In [53]:
d3

,manu,mpg,cyl,disp,hp,drat,weight,qsec,vs,am,gear,carb,Half qsec
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4,8.230
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4,8.510
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1,9.305
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1,9.720
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2,8.510
5,Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1,10.110
6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4,7.920
7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2,10.000
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2,11.450
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4,9.150
10,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4,9.450
11,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3,8.700
12,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3,8.800
13,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3,9.000
14,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4,8.990
15,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4,8.910
16,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4,8.710
17,Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1,9.735
18,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2,9.260
19,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1,9.950
20,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1,10.005
21,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2,8.435
22,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2,8.650
23,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4,7.705
24,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2,8.525
25,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1,9.450
26,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2,8.350
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2,8.450
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4,7.250
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6,7.750
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8,7.300
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2,9.300

In [54]:
d3["Car type"] = d3["am"].apply(lambda x: "Automatic" if x==1 else "Manual")

In [55]:
d3

,manu,mpg,cyl,disp,hp,drat,weight,qsec,vs,am,gear,carb,Half qsec,Car type
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4,8.230,Automatic
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4,8.510,Automatic
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1,9.305,Automatic
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1,9.720,Manual
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2,8.510,Manual
5,Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1,10.110,Manual
6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4,7.920,Manual
7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2,10.000,Manual
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2,11.450,Manual
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4,9.150,Manual
10,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4,9.450,Manual
11,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3,8.700,Manual
12,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3,8.800,Manual
13,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3,9.000,Manual
14,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4,8.990,Manual
15,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4,8.910,Manual
16,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4,8.710,Manual
17,Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1,9.735,Automatic
18,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2,9.260,Automatic
19,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1,9.950,Automatic
20,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1,10.005,Manual
21,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2,8.435,Manual
22,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2,8.650,Manual
23,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4,7.705,Manual
24,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2,8.525,Manual
25,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1,9.450,Automatic
26,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2,8.350,Automatic
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2,8.450,Automatic
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4,7.250,Automatic
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6,7.750,Automatic
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8,7.300,Automatic
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2,9.300,Automatic

In [56]:
d3["disp"] = d3["disp"] - 10
d3

,manu,mpg,cyl,disp,hp,drat,weight,qsec,vs,am,gear,carb,Half qsec,Car type
0,Mazda RX4,21.0,6,150.0,110,3.90,2.620,16.46,0,1,4,4,8.230,Automatic
1,Mazda RX4 Wag,21.0,6,150.0,110,3.90,2.875,17.02,0,1,4,4,8.510,Automatic
2,Datsun 710,22.8,4,98.0,93,3.85,2.320,18.61,1,1,4,1,9.305,Automatic
3,Hornet 4 Drive,21.4,6,248.0,110,3.08,3.215,19.44,1,0,3,1,9.720,Manual
4,Hornet Sportabout,18.7,8,350.0,175,3.15,3.440,17.02,0,0,3,2,8.510,Manual
5,Valiant,18.1,6,215.0,105,2.76,3.460,20.22,1,0,3,1,10.110,Manual
6,Duster 360,14.3,8,350.0,245,3.21,3.570,15.84,0,0,3,4,7.920,Manual
7,Merc 240D,24.4,4,136.7,62,3.69,3.190,20.00,1,0,4,2,10.000,Manual
8,Merc 230,22.8,4,130.8,95,3.92,3.150,22.90,1,0,4,2,11.450,Manual
9,Merc 280,19.2,6,157.6,123,3.92,3.440,18.30,1,0,4,4,9.150,Manual
10,Merc 280C,17.8,6,157.6,123,3.92,3.440,18.90,1,0,4,4,9.450,Manual
11,Merc 450SE,16.4,8,265.8,180,3.07,4.070,17.40,0,0,3,3,8.700,Manual
12,Merc 450SL,17.3,8,265.8,180,3.07,3.730,17.60,0,0,3,3,8.800,Manual
13,Merc 450SLC,15.2,8,265.8,180,3.07,3.780,18.00,0,0,3,3,9.000,Manual
14,Cadillac Fleetwood,10.4,8,462.0,205,2.93,5.250,17.98,0,0,3,4,8.990,Manual
15,Lincoln Continental,10.4,8,450.0,215,3.00,5.424,17.82,0,0,3,4,8.910,Manual
16,Chrysler Imperial,14.7,8,430.0,230,3.23,5.345,17.42,0,0,3,4,8.710,Manual
17,Fiat 128,32.4,4,68.7,66,4.08,2.200,19.47,1,1,4,1,9.735,Automatic
18,Honda Civic,30.4,4,65.7,52,4.93,1.615,18.52,1,1,4,2,9.260,Automatic
19,Toyota Corolla,33.9,4,61.1,65,4.22,1.835,19.90,1,1,4,1,9.950,Automatic
20,Toyota Corona,21.5,4,110.1,97,3.70,2.465,20.01,1,0,3,1,10.005,Manual
21,Dodge Challenger,15.5,8,308.0,150,2.76,3.520,16.87,0,0,3,2,8.435,Manual
22,AMC Javelin,15.2,8,294.0,150,3.15,3.435,17.30,0,0,3,2,8.650,Manual
23,Camaro Z28,13.3,8,340.0,245,3.73,3.840,15.41,0,0,3,4,7.705,Manual
24,Pontiac Firebird,19.2,8,390.0,175,3.08,3.845,17.05,0,0,3,2,8.525,Manual
25,Fiat X1-9,27.3,4,69.0,66,4.08,1.935,18.90,1,1,4,1,9.450,Automatic
26,Porsche 914-2,26.0,4,110.3,91,4.43,2.140,16.70,0,1,5,2,8.350,Automatic
27,Lotus Europa,30.4,4,85.1,113,3.77,1.513,16.90,1,1,5,2,8.450,Automatic
28,Ford Pantera L,15.8,8,341.0,264,4.22,3.170,14.50,0,1,5,4,7.250,Automatic
29,Ferrari Dino,19.7,6,135.0,175,3.62,2.770,15.50,0,1,5,6,7.750,Automatic
30,Maserati Bora,15.0,8,291.0,335,3.54,3.570,14.60,0,1,5,8,7.300,Automatic
31,Volvo 142E,21.4,4,111.0,109,4.11,2.780,18.60,1,1,4,2,9.300,Automatic

In [57]:
del d3["Half qsec"]
d3

,manu,mpg,cyl,disp,hp,drat,weight,qsec,vs,am,gear,carb,Car type
0,Mazda RX4,21.0,6,150.0,110,3.90,2.620,16.46,0,1,4,4,Automatic
1,Mazda RX4 Wag,21.0,6,150.0,110,3.90,2.875,17.02,0,1,4,4,Automatic
2,Datsun 710,22.8,4,98.0,93,3.85,2.320,18.61,1,1,4,1,Automatic
3,Hornet 4 Drive,21.4,6,248.0,110,3.08,3.215,19.44,1,0,3,1,Manual
4,Hornet Sportabout,18.7,8,350.0,175,3.15,3.440,17.02,0,0,3,2,Manual
5,Valiant,18.1,6,215.0,105,2.76,3.460,20.22,1,0,3,1,Manual
6,Duster 360,14.3,8,350.0,245,3.21,3.570,15.84,0,0,3,4,Manual
7,Merc 240D,24.4,4,136.7,62,3.69,3.190,20.00,1,0,4,2,Manual
8,Merc 230,22.8,4,130.8,95,3.92,3.150,22.90,1,0,4,2,Manual
9,Merc 280,19.2,6,157.6,123,3.92,3.440,18.30,1,0,4,4,Manual
10,Merc 280C,17.8,6,157.6,123,3.92,3.440,18.90,1,0,4,4,Manual
11,Merc 450SE,16.4,8,265.8,180,3.07,4.070,17.40,0,0,3,3,Manual
12,Merc 450SL,17.3,8,265.8,180,3.07,3.730,17.60,0,0,3,3,Manual
13,Merc 450SLC,15.2,8,265.8,180,3.07,3.780,18.00,0,0,3,3,Manual
14,Cadillac Fleetwood,10.4,8,462.0,205,2.93,5.250,17.98,0,0,3,4,Manual
15,Lincoln Continental,10.4,8,450.0,215,3.00,5.424,17.82,0,0,3,4,Manual
16,Chrysler Imperial,14.7,8,430.0,230,3.23,5.345,17.42,0,0,3,4,Manual
17,Fiat 128,32.4,4,68.7,66,4.08,2.200,19.47,1,1,4,1,Automatic
18,Honda Civic,30.4,4,65.7,52,4.93,1.615,18.52,1,1,4,2,Automatic
19,Toyota Corolla,33.9,4,61.1,65,4.22,1.835,19.90,1,1,4,1,Automatic
20,Toyota Corona,21.5,4,110.1,97,3.70,2.465,20.01,1,0,3,1,Manual
21,Dodge Challenger,15.5,8,308.0,150,2.76,3.520,16.87,0,0,3,2,Manual
22,AMC Javelin,15.2,8,294.0,150,3.15,3.435,17.30,0,0,3,2,Manual
23,Camaro Z28,13.3,8,340.0,245,3.73,3.840,15.41,0,0,3,4,Manual
24,Pontiac Firebird,19.2,8,390.0,175,3.08,3.845,17.05,0,0,3,2,Manual
25,Fiat X1-9,27.3,4,69.0,66,4.08,1.935,18.90,1,1,4,1,Automatic
26,Porsche 914-2,26.0,4,110.3,91,4.43,2.140,16.70,0,1,5,2,Automatic
27,Lotus Europa,30.4,4,85.1,113,3.77,1.513,16.90,1,1,5,2,Automatic
28,Ford Pantera L,15.8,8,341.0,264,4.22,3.170,14.50,0,1,5,4,Automatic
29,Ferrari Dino,19.7,6,135.0,175,3.62,2.770,15.50,0,1,5,6,Automatic
30,Maserati Bora,15.0,8,291.0,335,3.54,3.570,14.60,0,1,5,8,Automatic
31,Volvo 142E,21.4,4,111.0,109,4.11,2.780,18.60,1,1,4,2,Automatic

In [58]:
d3.drop(columns=["vs","am"])

,manu,mpg,cyl,disp,hp,drat,weight,qsec,gear,carb,Car type
0,Mazda RX4,21.0,6,150.0,110,3.90,2.620,16.46,4,4,Automatic
1,Mazda RX4 Wag,21.0,6,150.0,110,3.90,2.875,17.02,4,4,Automatic
2,Datsun 710,22.8,4,98.0,93,3.85,2.320,18.61,4,1,Automatic
3,Hornet 4 Drive,21.4,6,248.0,110,3.08,3.215,19.44,3,1,Manual
4,Hornet Sportabout,18.7,8,350.0,175,3.15,3.440,17.02,3,2,Manual
5,Valiant,18.1,6,215.0,105,2.76,3.460,20.22,3,1,Manual
6,Duster 360,14.3,8,350.0,245,3.21,3.570,15.84,3,4,Manual
7,Merc 240D,24.4,4,136.7,62,3.69,3.190,20.00,4,2,Manual
8,Merc 230,22.8,4,130.8,95,3.92,3.150,22.90,4,2,Manual
9,Merc 280,19.2,6,157.6,123,3.92,3.440,18.30,4,4,Manual
10,Merc 280C,17.8,6,157.6,123,3.92,3.440,18.90,4,4,Manual
11,Merc 450SE,16.4,8,265.8,180,3.07,4.070,17.40,3,3,Manual
12,Merc 450SL,17.3,8,265.8,180,3.07,3.730,17.60,3,3,Manual
13,Merc 450SLC,15.2,8,265.8,180,3.07,3.780,18.00,3,3,Manual
14,Cadillac Fleetwood,10.4,8,462.0,205,2.93,5.250,17.98,3,4,Manual
15,Lincoln Continental,10.4,8,450.0,215,3.00,5.424,17.82,3,4,Manual
16,Chrysler Imperial,14.7,8,430.0,230,3.23,5.345,17.42,3,4,Manual
17,Fiat 128,32.4,4,68.7,66,4.08,2.200,19.47,4,1,Automatic
18,Honda Civic,30.4,4,65.7,52,4.93,1.615,18.52,4,2,Automatic
19,Toyota Corolla,33.9,4,61.1,65,4.22,1.835,19.90,4,1,Automatic
20,Toyota Corona,21.5,4,110.1,97,3.70,2.465,20.01,3,1,Manual
21,Dodge Challenger,15.5,8,308.0,150,2.76,3.520,16.87,3,2,Manual
22,AMC Javelin,15.2,8,294.0,150,3.15,3.435,17.30,3,2,Manual
23,Camaro Z28,13.3,8,340.0,245,3.73,3.840,15.41,3,4,Manual
24,Pontiac Firebird,19.2,8,390.0,175,3.08,3.845,17.05,3,2,Manual
25,Fiat X1-9,27.3,4,69.0,66,4.08,1.935,18.90,4,1,Automatic
26,Porsche 914-2,26.0,4,110.3,91,4.43,2.140,16.70,5,2,Automatic
27,Lotus Europa,30.4,4,85.1,113,3.77,1.513,16.90,5,2,Automatic
28,Ford Pantera L,15.8,8,341.0,264,4.22,3.170,14.50,5,4,Automatic
29,Ferrari Dino,19.7,6,135.0,175,3.62,2.770,15.50,5,6,Automatic
30,Maserati Bora,15.0,8,291.0,335,3.54,3.570,14.60,5,8,Automatic
31,Volvo 142E,21.4,4,111.0,109,4.11,2.780,18.60,4,2,Automatic

In [59]:
d3

,manu,mpg,cyl,disp,hp,drat,weight,qsec,vs,am,gear,carb,Car type
0,Mazda RX4,21.0,6,150.0,110,3.90,2.620,16.46,0,1,4,4,Automatic
1,Mazda RX4 Wag,21.0,6,150.0,110,3.90,2.875,17.02,0,1,4,4,Automatic
2,Datsun 710,22.8,4,98.0,93,3.85,2.320,18.61,1,1,4,1,Automatic
3,Hornet 4 Drive,21.4,6,248.0,110,3.08,3.215,19.44,1,0,3,1,Manual
4,Hornet Sportabout,18.7,8,350.0,175,3.15,3.440,17.02,0,0,3,2,Manual
5,Valiant,18.1,6,215.0,105,2.76,3.460,20.22,1,0,3,1,Manual
6,Duster 360,14.3,8,350.0,245,3.21,3.570,15.84,0,0,3,4,Manual
7,Merc 240D,24.4,4,136.7,62,3.69,3.190,20.00,1,0,4,2,Manual
8,Merc 230,22.8,4,130.8,95,3.92,3.150,22.90,1,0,4,2,Manual
9,Merc 280,19.2,6,157.6,123,3.92,3.440,18.30,1,0,4,4,Manual
10,Merc 280C,17.8,6,157.6,123,3.92,3.440,18.90,1,0,4,4,Manual
11,Merc 450SE,16.4,8,265.8,180,3.07,4.070,17.40,0,0,3,3,Manual
12,Merc 450SL,17.3,8,265.8,180,3.07,3.730,17.60,0,0,3,3,Manual
13,Merc 450SLC,15.2,8,265.8,180,3.07,3.780,18.00,0,0,3,3,Manual
14,Cadillac Fleetwood,10.4,8,462.0,205,2.93,5.250,17.98,0,0,3,4,Manual
15,Lincoln Continental,10.4,8,450.0,215,3.00,5.424,17.82,0,0,3,4,Manual
16,Chrysler Imperial,14.7,8,430.0,230,3.23,5.345,17.42,0,0,3,4,Manual
17,Fiat 128,32.4,4,68.7,66,4.08,2.200,19.47,1,1,4,1,Automatic
18,Honda Civic,30.4,4,65.7,52,4.93,1.615,18.52,1,1,4,2,Automatic
19,Toyota Corolla,33.9,4,61.1,65,4.22,1.835,19.90,1,1,4,1,Automatic
20,Toyota Corona,21.5,4,110.1,97,3.70,2.465,20.01,1,0,3,1,Manual
21,Dodge Challenger,15.5,8,308.0,150,2.76,3.520,16.87,0,0,3,2,Manual
22,AMC Javelin,15.2,8,294.0,150,3.15,3.435,17.30,0,0,3,2,Manual
23,Camaro Z28,13.3,8,340.0,245,3.73,3.840,15.41,0,0,3,4,Manual
24,Pontiac Firebird,19.2,8,390.0,175,3.08,3.845,17.05,0,0,3,2,Manual
25,Fiat X1-9,27.3,4,69.0,66,4.08,1.935,18.90,1,1,4,1,Automatic
26,Porsche 914-2,26.0,4,110.3,91,4.43,2.140,16.70,0,1,5,2,Automatic
27,Lotus Europa,30.4,4,85.1,113,3.77,1.513,16.90,1,1,5,2,Automatic
28,Ford Pantera L,15.8,8,341.0,264,4.22,3.170,14.50,0,1,5,4,Automatic
29,Ferrari Dino,19.7,6,135.0,175,3.62,2.770,15.50,0,1,5,6,Automatic
30,Maserati Bora,15.0,8,291.0,335,3.54,3.570,14.60,0,1,5,8,Automatic
31,Volvo 142E,21.4,4,111.0,109,4.11,2.780,18.60,1,1,4,2,Automatic

In [60]:
calculate min,max value of mpg column

SyntaxError: invalid syntax (2715035949.py, line 1)

In [61]:
d3.mpg.mean()

np.float64(20.090625000000003)

In [62]:
d3.mpg.median()

19.2

In [63]:
d3.mpg.sum()

np.float64(642.9000000000001)

In [64]:
d3.mpg.max()

33.9

In [65]:
d3.mpg.min()

10.4

In [66]:
d3.shape

(32, 13)

In [67]:
d3.head(5)

,manu,mpg,cyl,disp,hp,drat,weight,qsec,vs,am,gear,carb,Car type
0,Mazda RX4,21.0,6,150.0,110,3.90,2.620,16.46,0,1,4,4,Automatic
1,Mazda RX4 Wag,21.0,6,150.0,110,3.90,2.875,17.02,0,1,4,4,Automatic
2,Datsun 710,22.8,4,98.0,93,3.85,2.320,18.61,1,1,4,1,Automatic
3,Hornet 4 Drive,21.4,6,248.0,110,3.08,3.215,19.44,1,0,3,1,Manual
4,Hornet Sportabout,18.7,8,350.0,175,3.15,3.440,17.02,0,0,3,2,Manual

In [68]:
# 1st five row and column

dataframe slicing:
1) iloc: using index values of rows and column
    var.iloc[rst:rsp:rss,cst:csp:css]

default start value:0
        dtop value: upto end
        step size: 1

SyntaxError: unmatched ')' (3361940237.py, line 4)

In [69]:
d3.iloc[:5,:5]   #slicing

                manu   mpg  cyl   disp   hp
0          Mazda RX4  21.0    6  150.0  110
1      Mazda RX4 Wag  21.0    6  150.0  110
2         Datsun 710  22.8    4   98.0   93
3     Hornet 4 Drive  21.4    6  248.0  110
4  Hornet Sportabout  18.7    8  350.0  175

In [70]:
#exrcat all rows wit last 5 columns

d3.iloc[:,-5:]

    vs  am  gear  carb   Car type
0    0   1     4     4  Automatic
1    0   1     4     4  Automatic
2    1   1     4     1  Automatic
3    1   0     3     1     Manual
4    0   0     3     2     Manual
5    1   0     3     1     Manual
6    0   0     3     4     Manual
7    1   0     4     2     Manual
8    1   0     4     2     Manual
9    1   0     4     4     Manual
10   1   0     4     4     Manual
11   0   0     3     3     Manual
12   0   0     3     3     Manual
13   0   0     3     3     Manual
14   0   0     3     4     Manual
15   0   0     3     4     Manual
16   0   0     3     4     Manual
17   1   1     4     1  Automatic
18   1   1     4     2  Automatic
19   1   1     4     1  Automatic
20   1   0     3     1     Manual
21   0   0     3     2     Manual
22   0   0     3     2     Manual
23   0   0     3     4     Manual
24   0   0     3     2     Manual
25   1   1     4     1  Automatic
26   0   1     5     2  Automatic
27   1   1     5     2  Automatic
28   0   1     5     4  Automatic
29   0   1     5     6  Automatic
30   0   1     5     8  Automatic
31   1   1     4     2  Automatic

In [71]:
d3.iloc[::-1,::-1]

,Car type,carb,gear,am,vs,qsec,weight,drat,hp,disp,cyl,mpg,manu
31,Automatic,2,4,1,1,18.60,2.780,4.11,109,111.0,4,21.4,Volvo 142E
30,Automatic,8,5,1,0,14.60,3.570,3.54,335,291.0,8,15.0,Maserati Bora
29,Automatic,6,5,1,0,15.50,2.770,3.62,175,135.0,6,19.7,Ferrari Dino
28,Automatic,4,5,1,0,14.50,3.170,4.22,264,341.0,8,15.8,Ford Pantera L
27,Automatic,2,5,1,1,16.90,1.513,3.77,113,85.1,4,30.4,Lotus Europa
26,Automatic,2,5,1,0,16.70,2.140,4.43,91,110.3,4,26.0,Porsche 914-2
25,Automatic,1,4,1,1,18.90,1.935,4.08,66,69.0,4,27.3,Fiat X1-9
24,Manual,2,3,0,0,17.05,3.845,3.08,175,390.0,8,19.2,Pontiac Firebird
23,Manual,4,3,0,0,15.41,3.840,3.73,245,340.0,8,13.3,Camaro Z28
22,Manual,2,3,0,0,17.30,3.435,3.15,150,294.0,8,15.2,AMC Javelin
21,Manual,2,3,0,0,16.87,3.520,2.76,150,308.0,8,15.5,Dodge Challenger
20,Manual,1,3,0,1,20.01,2.465,3.70,97,110.1,4,21.5,Toyota Corona
19,Automatic,1,4,1,1,19.90,1.835,4.22,65,61.1,4,33.9,Toyota Corolla
18,Automatic,2,4,1,1,18.52,1.615,4.93,52,65.7,4,30.4,Honda Civic
17,Automatic,1,4,1,1,19.47,2.200,4.08,66,68.7,4,32.4,Fiat 128
16,Manual,4,3,0,0,17.42,5.345,3.23,230,430.0,8,14.7,Chrysler Imperial
15,Manual,4,3,0,0,17.82,5.424,3.00,215,450.0,8,10.4,Lincoln Continental
14,Manual,4,3,0,0,17.98,5.250,2.93,205,462.0,8,10.4,Cadillac Fleetwood
13,Manual,3,3,0,0,18.00,3.780,3.07,180,265.8,8,15.2,Merc 450SLC
12,Manual,3,3,0,0,17.60,3.730,3.07,180,265.8,8,17.3,Merc 450SL
11,Manual,3,3,0,0,17.40,4.070,3.07,180,265.8,8,16.4,Merc 450SE
10,Manual,4,4,0,1,18.90,3.440,3.92,123,157.6,6,17.8,Merc 280C
9,Manual,4,4,0,1,18.30,3.440,3.92,123,157.6,6,19.2,Merc 280
8,Manual,2,4,0,1,22.90,3.150,3.92,95,130.8,4,22.8,Merc 230
7,Manual,2,4,0,1,20.00,3.190,3.69,62,136.7,4,24.4,Merc 240D
6,Manual,4,3,0,0,15.84,3.570,3.21,245,350.0,8,14.3,Duster 360
5,Manual,1,3,0,1,20.22,3.460,2.76,105,215.0,6,18.1,Valiant
4,Manual,2,3,0,0,17.02,3.440,3.15,175,350.0,8,18.7,Hornet Sportabout
3,Manual,1,3,0,1,19.44,3.215,3.08,110,248.0,6,21.4,Hornet 4 Drive
2,Automatic,1,4,1,1,18.61,2.320,3.85,93,98.0,4,22.8,Datsun 710
1,Automatic,4,4,1,0,17.02,2.875,3.90,110,150.0,6,21.0,Mazda RX4 Wag
0,Automatic,4,4,1,0,16.46,2.620,3.90,110,150.0,6,21.0,Mazda RX4

In [72]:
# print even indexed rows and odd indexed columns
d3.iloc[0::2,1::2]

     mpg   disp  drat   qsec  am  carb
0   21.0  150.0  3.90  16.46   1     4
2   22.8   98.0  3.85  18.61   1     1
4   18.7  350.0  3.15  17.02   0     2
6   14.3  350.0  3.21  15.84   0     4
8   22.8  130.8  3.92  22.90   0     2
10  17.8  157.6  3.92  18.90   0     4
12  17.3  265.8  3.07  17.60   0     3
14  10.4  462.0  2.93  17.98   0     4
16  14.7  430.0  3.23  17.42   0     4
18  30.4   65.7  4.93  18.52   1     2
20  21.5  110.1  3.70  20.01   0     1
22  15.2  294.0  3.15  17.30   0     2
24  19.2  390.0  3.08  17.05   0     2
26  26.0  110.3  4.43  16.70   1     2
28  15.8  341.0  4.22  14.50   1     4
30  15.0  291.0  3.54  14.60   1     8

In [73]:
#rows = [2,7,11,15,20,23,28]
#columns = [2,6,9,11]

d3.iloc[[2,7,11,15,20,23,28],[2,6,9,11]]

    cyl  weight  am  carb
2     4   2.320   1     1
7     4   3.190   0     2
11    8   4.070   0     3
15    8   5.424   0     4
20    4   2.465   0     1
23    8   3.840   0     4
28    8   3.170   1     4

loc: extracting data by location nam

var.loc[strating name:ending name, strating name:ending name]

In [74]:
#extract 1st 10 rows with 1st 4 columns

d3.loc[0:9,"manu":"disp"]

                manu   mpg  cyl   disp
0          Mazda RX4  21.0    6  150.0
1      Mazda RX4 Wag  21.0    6  150.0
2         Datsun 710  22.8    4   98.0
3     Hornet 4 Drive  21.4    6  248.0
4  Hornet Sportabout  18.7    8  350.0
5            Valiant  18.1    6  215.0
6         Duster 360  14.3    8  350.0
7          Merc 240D  24.4    4  136.7
8           Merc 230  22.8    4  130.8
9           Merc 280  19.2    6  157.6

In [75]:
d3.loc[31:1,"Car type":"manu"]

Empty DataFrame
Columns: []
Index: []

In [76]:
d3.loc[30:1,"Car type":"manu"]

Empty DataFrame
Columns: []
Index: []

In [77]:
d3.loc[::-1 ,"Car type":"manu":-1]

,Car type,carb,gear,am,vs,qsec,weight,drat,hp,disp,cyl,mpg,manu
31,Automatic,2,4,1,1,18.60,2.780,4.11,109,111.0,4,21.4,Volvo 142E
30,Automatic,8,5,1,0,14.60,3.570,3.54,335,291.0,8,15.0,Maserati Bora
29,Automatic,6,5,1,0,15.50,2.770,3.62,175,135.0,6,19.7,Ferrari Dino
28,Automatic,4,5,1,0,14.50,3.170,4.22,264,341.0,8,15.8,Ford Pantera L
27,Automatic,2,5,1,1,16.90,1.513,3.77,113,85.1,4,30.4,Lotus Europa
26,Automatic,2,5,1,0,16.70,2.140,4.43,91,110.3,4,26.0,Porsche 914-2
25,Automatic,1,4,1,1,18.90,1.935,4.08,66,69.0,4,27.3,Fiat X1-9
24,Manual,2,3,0,0,17.05,3.845,3.08,175,390.0,8,19.2,Pontiac Firebird
23,Manual,4,3,0,0,15.41,3.840,3.73,245,340.0,8,13.3,Camaro Z28
22,Manual,2,3,0,0,17.30,3.435,3.15,150,294.0,8,15.2,AMC Javelin
21,Manual,2,3,0,0,16.87,3.520,2.76,150,308.0,8,15.5,Dodge Challenger
20,Manual,1,3,0,1,20.01,2.465,3.70,97,110.1,4,21.5,Toyota Corona
19,Automatic,1,4,1,1,19.90,1.835,4.22,65,61.1,4,33.9,Toyota Corolla
18,Automatic,2,4,1,1,18.52,1.615,4.93,52,65.7,4,30.4,Honda Civic
17,Automatic,1,4,1,1,19.47,2.200,4.08,66,68.7,4,32.4,Fiat 128
16,Manual,4,3,0,0,17.42,5.345,3.23,230,430.0,8,14.7,Chrysler Imperial
15,Manual,4,3,0,0,17.82,5.424,3.00,215,450.0,8,10.4,Lincoln Continental
14,Manual,4,3,0,0,17.98,5.250,2.93,205,462.0,8,10.4,Cadillac Fleetwood
13,Manual,3,3,0,0,18.00,3.780,3.07,180,265.8,8,15.2,Merc 450SLC
12,Manual,3,3,0,0,17.60,3.730,3.07,180,265.8,8,17.3,Merc 450SL
11,Manual,3,3,0,0,17.40,4.070,3.07,180,265.8,8,16.4,Merc 450SE
10,Manual,4,4,0,1,18.90,3.440,3.92,123,157.6,6,17.8,Merc 280C
9,Manual,4,4,0,1,18.30,3.440,3.92,123,157.6,6,19.2,Merc 280
8,Manual,2,4,0,1,22.90,3.150,3.92,95,130.8,4,22.8,Merc 230
7,Manual,2,4,0,1,20.00,3.190,3.69,62,136.7,4,24.4,Merc 240D
6,Manual,4,3,0,0,15.84,3.570,3.21,245,350.0,8,14.3,Duster 360
5,Manual,1,3,0,1,20.22,3.460,2.76,105,215.0,6,18.1,Valiant
4,Manual,2,3,0,0,17.02,3.440,3.15,175,350.0,8,18.7,Hornet Sportabout
3,Manual,1,3,0,1,19.44,3.215,3.08,110,248.0,6,21.4,Hornet 4 Drive
2,Automatic,1,4,1,1,18.61,2.320,3.85,93,98.0,4,22.8,Datsun 710
1,Automatic,4,4,1,0,17.02,2.875,3.90,110,150.0,6,21.0,Mazda RX4 Wag
0,Automatic,4,4,1,0,16.46,2.620,3.90,110,150.0,6,21.0,Mazda RX4

In [78]:
d3[d3["gear"]==4]

,manu,mpg,cyl,disp,hp,drat,weight,qsec,vs,am,gear,carb,Car type
0,Mazda RX4,21.0,6,150.0,110,3.90,2.620,16.46,0,1,4,4,Automatic
1,Mazda RX4 Wag,21.0,6,150.0,110,3.90,2.875,17.02,0,1,4,4,Automatic
2,Datsun 710,22.8,4,98.0,93,3.85,2.320,18.61,1,1,4,1,Automatic
7,Merc 240D,24.4,4,136.7,62,3.69,3.190,20.00,1,0,4,2,Manual
8,Merc 230,22.8,4,130.8,95,3.92,3.150,22.90,1,0,4,2,Manual
9,Merc 280,19.2,6,157.6,123,3.92,3.440,18.30,1,0,4,4,Manual
10,Merc 280C,17.8,6,157.6,123,3.92,3.440,18.90,1,0,4,4,Manual
17,Fiat 128,32.4,4,68.7,66,4.08,2.200,19.47,1,1,4,1,Automatic
18,Honda Civic,30.4,4,65.7,52,4.93,1.615,18.52,1,1,4,2,Automatic
19,Toyota Corolla,33.9,4,61.1,65,4.22,1.835,19.90,1,1,4,1,Automatic
25,Fiat X1-9,27.3,4,69.0,66,4.08,1.935,18.90,1,1,4,1,Automatic
31,Volvo 142E,21.4,4,111.0,109,4.11,2.780,18.60,1,1,4,2,Automatic

In [79]:
# try to extract  4 gear with 6 cyl

d3[(d3["gear"]==4) & (d3["cyl"]==6)]

,manu,mpg,cyl,disp,hp,drat,weight,qsec,vs,am,gear,carb,Car type
0,Mazda RX4,21.0,6,150.0,110,3.90,2.620,16.46,0,1,4,4,Automatic
1,Mazda RX4 Wag,21.0,6,150.0,110,3.90,2.875,17.02,0,1,4,4,Automatic
9,Merc 280,19.2,6,157.6,123,3.92,3.440,18.30,1,0,4,4,Manual
10,Merc 280C,17.8,6,157.6,123,3.92,3.440,18.90,1,0,4,4,Manual

In [80]:
# extract data either 2 carb or automatic car details

d3[(d3["carb"]==2) | (d3["Car type"]=="Automatic")]

,manu,mpg,cyl,disp,hp,drat,weight,qsec,vs,am,gear,carb,Car type
0,Mazda RX4,21.0,6,150.0,110,3.90,2.620,16.46,0,1,4,4,Automatic
1,Mazda RX4 Wag,21.0,6,150.0,110,3.90,2.875,17.02,0,1,4,4,Automatic
2,Datsun 710,22.8,4,98.0,93,3.85,2.320,18.61,1,1,4,1,Automatic
4,Hornet Sportabout,18.7,8,350.0,175,3.15,3.440,17.02,0,0,3,2,Manual
7,Merc 240D,24.4,4,136.7,62,3.69,3.190,20.00,1,0,4,2,Manual
8,Merc 230,22.8,4,130.8,95,3.92,3.150,22.90,1,0,4,2,Manual
17,Fiat 128,32.4,4,68.7,66,4.08,2.200,19.47,1,1,4,1,Automatic
18,Honda Civic,30.4,4,65.7,52,4.93,1.615,18.52,1,1,4,2,Automatic
19,Toyota Corolla,33.9,4,61.1,65,4.22,1.835,19.90,1,1,4,1,Automatic
21,Dodge Challenger,15.5,8,308.0,150,2.76,3.520,16.87,0,0,3,2,Manual
22,AMC Javelin,15.2,8,294.0,150,3.15,3.435,17.30,0,0,3,2,Manual
24,Pontiac Firebird,19.2,8,390.0,175,3.08,3.845,17.05,0,0,3,2,Manual
25,Fiat X1-9,27.3,4,69.0,66,4.08,1.935,18.90,1,1,4,1,Automatic
26,Porsche 914-2,26.0,4,110.3,91,4.43,2.140,16.70,0,1,5,2,Automatic
27,Lotus Europa,30.4,4,85.1,113,3.77,1.513,16.90,1,1,5,2,Automatic
28,Ford Pantera L,15.8,8,341.0,264,4.22,3.170,14.50,0,1,5,4,Automatic
29,Ferrari Dino,19.7,6,135.0,175,3.62,2.770,15.50,0,1,5,6,Automatic
30,Maserati Bora,15.0,8,291.0,335,3.54,3.570,14.60,0,1,5,8,Automatic
31,Volvo 142E,21.4,4,111.0,109,4.11,2.780,18.60,1,1,4,2,Automatic

In [82]:
#extract data whose hp between 110 to 120
d3[(d3["hp"]>= 110) & (d3["hp"]<=120)]

,manu,mpg,cyl,disp,hp,drat,weight,qsec,vs,am,gear,carb,Car type
0,Mazda RX4,21.0,6,150.0,110,3.90,2.620,16.46,0,1,4,4,Automatic
1,Mazda RX4 Wag,21.0,6,150.0,110,3.90,2.875,17.02,0,1,4,4,Automatic
3,Hornet 4 Drive,21.4,6,248.0,110,3.08,3.215,19.44,1,0,3,1,Manual
27,Lotus Europa,30.4,4,85.1,113,3.77,1.513,16.90,1,1,5,2,Automatic

In [85]:
#extract data weight between 2 to 3 or 6 cyl

d3[(d3["weight"].between(2,3)) | (d3["cyl"]==6)]

,manu,mpg,cyl,disp,hp,drat,weight,qsec,vs,am,gear,carb,Car type
0,Mazda RX4,21.0,6,150.0,110,3.90,2.620,16.46,0,1,4,4,Automatic
1,Mazda RX4 Wag,21.0,6,150.0,110,3.90,2.875,17.02,0,1,4,4,Automatic
2,Datsun 710,22.8,4,98.0,93,3.85,2.320,18.61,1,1,4,1,Automatic
3,Hornet 4 Drive,21.4,6,248.0,110,3.08,3.215,19.44,1,0,3,1,Manual
5,Valiant,18.1,6,215.0,105,2.76,3.460,20.22,1,0,3,1,Manual
9,Merc 280,19.2,6,157.6,123,3.92,3.440,18.30,1,0,4,4,Manual
10,Merc 280C,17.8,6,157.6,123,3.92,3.440,18.90,1,0,4,4,Manual
17,Fiat 128,32.4,4,68.7,66,4.08,2.200,19.47,1,1,4,1,Automatic
20,Toyota Corona,21.5,4,110.1,97,3.70,2.465,20.01,1,0,3,1,Manual
26,Porsche 914-2,26.0,4,110.3,91,4.43,2.140,16.70,0,1,5,2,Automatic
29,Ferrari Dino,19.7,6,135.0,175,3.62,2.770,15.50,0,1,5,6,Automatic
31,Volvo 142E,21.4,4,111.0,109,4.11,2.780,18.60,1,1,4,2,Automatic

In [91]:
d7=pd.read_csv(r"C:\\Users\\ar543\\Downloads\\insurance.csv")

d7

      age     sex   bmi  children smoker     region  expenses
0      19  female  27.9         0    yes  southwest  16884.92
1      18    male  33.8         1     no  southeast   1725.55
2      28    male  33.0         3     no  southeast   4449.46
3      33    male  22.7         0     no  northwest  21984.47
4      32    male  28.9         0     no  northwest   3866.86
...   ...     ...   ...       ...    ...        ...       ...
1333   50    male  31.0         3     no  northwest  10600.55
1334   18  female  31.9         0     no  northeast   2205.98
1335   18  female  36.9         0     no  southeast   1629.83
1336   21  female  25.8         0     no  southwest   2007.95
1337   61  female  29.1         0    yes  northwest  29141.36

[1338 rows x 7 columns]

In [92]:
d7.head()

   age     sex   bmi  children smoker     region  expenses
0   19  female  27.9         0    yes  southwest  16884.92
1   18    male  33.8         1     no  southeast   1725.55
2   28    male  33.0         3     no  southeast   4449.46
3   33    male  22.7         0     no  northwest  21984.47
4   32    male  28.9         0     no  northwest   3866.86

In [94]:
d7.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1338 non-null   int64
 1   sex       1338 non-null   object
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64
 4   smoker    1338 non-null   object
 5   region    1338 non-null   object
 6   expenses  1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB

In [95]:
d7.isna().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
expenses    0
dtype: int64

In [97]:
d7.duplicated().sum()

np.int64(1)

In [100]:
d7.drop_duplicates(inplace=True)
d7

      age     sex   bmi  children smoker     region  expenses
0      19  female  27.9         0    yes  southwest  16884.92
1      18    male  33.8         1     no  southeast   1725.55
2      28    male  33.0         3     no  southeast   4449.46
3      33    male  22.7         0     no  northwest  21984.47
4      32    male  28.9         0     no  northwest   3866.86
...   ...     ...   ...       ...    ...        ...       ...
1333   50    male  31.0         3     no  northwest  10600.55
1334   18  female  31.9         0     no  northeast   2205.98
1335   18  female  36.9         0     no  southeast   1629.83
1336   21  female  25.8         0     no  southwest   2007.95
1337   61  female  29.1         0    yes  northwest  29141.36

[1337 rows x 7 columns]

In [101]:
d7.dtypes

age           int64
sex          object
bmi         float64
children      int64
smoker       object
region       object
expenses    float64
dtype: object

In [102]:
d7.shape

(1337, 7)

In [113]:
# 1) each region wise total expense

d7.groupby("region")["expenses"].sum().sort_values(ascending=False)

region
southeast    5363689.80
northeast    4343668.64
northwest    4034072.37
southwest    4012754.82
Name: expenses, dtype: float64

In [110]:
d7["region"].unique()

array(['southwest', 'southeast', 'northwest', 'northeast'], dtype=object)

In [117]:
#gender wise average bmi and expenses

d7.groupby('sex')[['bmi','expenses']].mean().round(2)

          bmi  expenses
sex
female  30.38  12569.58
male    30.95  13975.00

In [122]:
#each region , each children and smoker class wise total expenses

d7.groupby(['region','children','smoker'])['expenses'].mean()

region     children  smoker
northeast  0         no         8072.292479
                     yes       28167.025385
           1         no         9898.238182
                     yes       32340.127273
           2         no        11669.296190
                     yes       22695.814444
           3         no         7653.362069
                     yes       34003.914000
           4         no        14485.194286
           5         no         6978.973333
northwest  0         no         7599.786916
                     yes       28333.342083
           1         no         7981.625846
                     yes       26470.358889
           2         no         9950.850182
                     yes       31031.635455
           3         no        10547.913333
                     yes       36160.173077
           4         no         9321.926000
                     yes       21472.480000
           5         no         8965.800000
southeast  0         no         7060.081624
                     yes       35515.494500
           1         no         8016.476164
                     yes       32503.010455
           2         no         7519.505833
                     yes       37619.046667
           3         no        11986.612083
                     yes       32551.445455
           4         no        14451.024000
           5         no        10115.441667
southwest  0         no         7754.155044
                     yes       30851.768800
           1         no         7647.231857
                     yes       34549.955000
           2         no         8946.972250
                     yes       37569.401765
           3         no         8650.186875
                     yes       21616.882000
           4         no         9281.694000
                     yes       29062.180000
           5         no         6932.858571
                     yes       19023.260000
Name: expenses, dtype: float64

In [126]:
pd.pivot_table(data=d7,index=['region'],columns=['smoker','children'],values='expenses',aggfunc='mean')

smoker              no                                                         \
children             0            1             2             3             4
region
northeast  8072.292479  9898.238182  11669.296190   7653.362069  14485.194286
northwest  7599.786916  7981.625846   9950.850182  10547.913333   9321.926000
southeast  7060.081624  8016.476164   7519.505833  11986.612083  14451.024000
southwest  7754.155044  7647.231857   8946.972250   8650.186875   9281.694000

smoker                            yes                              \
children              5             0             1             2
region
northeast   6978.973333  28167.025385  32340.127273  22695.814444
northwest   8965.800000  28333.342083  26470.358889  31031.635455
southeast  10115.441667  35515.494500  32503.010455  37619.046667
southwest   6932.858571  30851.768800  34549.955000  37569.401765

smoker
children              3         4         5
region
northeast  34003.914000       NaN       NaN
northwest  36160.173077  21472.48       NaN
southeast  32551.445455       NaN       NaN
southwest  21616.882000  29062.18  19023.26

In [135]:
sale1=pd.read_csv(r"C:\\Users\\ar543\\Downloads\\Sales Transactions-2017.csv")
sale2=pd.read_csv(r"C:\Users\ar543\Downloads\Sales Transactions-2018.csv")
sale3=pd.read_csv(r"C:\Users\ar543\Downloads\Sales Transactions-2019.csv")

In [132]:
sale1

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,1/4/2017,Sal:1,SOLANKI PLASTICS,DONA-VAI-9100,2,"1,690.00","3,380.00",NaN,"13,100.00"
1,1/4/2017,Sal:1,SOLANKI PLASTICS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
2,1/4/2017,Sal:2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23,"11,500.00",NaN,"30,990.00"
3,1/4/2017,Sal:2,SARNESWARA TRADERS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
4,1/4/2017,Sal:2,SARNESWARA TRADERS,DONA-VAI-9100,5,"1,690.00","8,450.00",NaN,NaN
...,...,...,...,...,...,...,...,...,...
47285,31/03/2018,Sal:10042,Vkp,10*10 SHEET,25,137,"3,425.00",NaN,"3,425.00"
47286,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47287,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47288,NaN,Total,NaN,NaN,"607,734.60","669,300.49","9,953,816.13","106,607.00","9,868,583.13"
47289,NaN,Total,NaN,NaN,"7,593,062.00","8,309,116.00","115,778,725.71","936,348.00","115,105,123.71"

In [133]:
sale2

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,1/4/2018,Sal:146,TP13,SILVER POUCH 9*12,50,85,"4,250.00",NaN,"66,724.00"
1,1/4/2018,Sal:146,TP13,RUBBER,5,290,"1,450.00",NaN,NaN
2,1/4/2018,Sal:146,TP13,DURGA 10*12 Blue,"1,600.00",5.5,"8,800.00",NaN,NaN
3,1/4/2018,Sal:146,TP13,DURGA 13*16 BLUE,400,11,"4,400.00",NaN,NaN
4,1/4/2018,Sal:146,TP13,10*12 SARAS-NAT,600,8.1,"4,860.00",NaN,NaN
...,...,...,...,...,...,...,...,...,...
44735,31/03/2019,Sal:9610,HAMPI FOODS,SPOON SOOFY,200,40,"8,000.00",NaN,NaN
44736,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44737,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44738,NaN,Total,NaN,NaN,"666,056.00","1,067,808.80","10,796,991.30","29,999.00","10,787,647.30"
44739,NaN,Total,NaN,NaN,"7,097,803.00","10,024,197.00","117,897,671.80","720,204.00","117,427,983.80"

In [136]:
sale3

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,1/4/2019,Sal:687,BALAJI PLASTICS,DONA-VAI-9100,1,"1,730.00","1,730.00",NaN,"3,460.00"
1,1/4/2019,Sal:687,BALAJI PLASTICS,SMART BOUL(48),1,"1,730.00","1,730.00",NaN,NaN
2,1/4/2019,Sal:688,BALAJI PLASTICS,Vishnu Ice,110,18.5,"2,035.00",NaN,"2,035.00"
3,,,28/3,,0,0,,,
4,1/4/2019,Sal:689,BALAJI PLASTICS,100LEAF -SP,3,585,"1,755.00",NaN,"1,755.00"
...,...,...,...,...,...,...,...,...,...
19171,10/10/2019,Sal:4935,K.SRIHARI,13*16 WHITE RK,400,16,"6,400.00",NaN,NaN
19172,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19173,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19174,NaN,Total,NaN,NaN,"99,284.90","175,381.65","2,203,649.50","20,680.00","2,189,014.50"
19175,NaN,Total,NaN,NaN,"2,710,193.00","5,519,888.40","53,360,791.40","672,984.00","52,830,224.40"

In [142]:
fd = pd.concat([sale1,sale2,sale3],ignore_index=True)
fd

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,1/4/2017,Sal:1,SOLANKI PLASTICS,DONA-VAI-9100,2,"1,690.00","3,380.00",NaN,"13,100.00"
1,1/4/2017,Sal:1,SOLANKI PLASTICS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
2,1/4/2017,Sal:2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23,"11,500.00",NaN,"30,990.00"
3,1/4/2017,Sal:2,SARNESWARA TRADERS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
4,1/4/2017,Sal:2,SARNESWARA TRADERS,DONA-VAI-9100,5,"1,690.00","8,450.00",NaN,NaN
...,...,...,...,...,...,...,...,...,...
111201,10/10/2019,Sal:4935,K.SRIHARI,13*16 WHITE RK,400,16,"6,400.00",NaN,NaN
111202,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
111203,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
111204,NaN,Total,NaN,NaN,"99,284.90","175,381.65","2,203,649.50","20,680.00","2,189,014.50"
111205,NaN,Total,NaN,NaN,"2,710,193.00","5,519,888.40","53,360,791.40","672,984.00","52,830,224.40"