In [ ]:
libraries:-they are collection of modules and functions to perform specific tasks.

pandas:-data manipulation
numpy(numerical python): multi-dimensional arrays and mathematical operations

matplotlib,seaborn,plotly:data visualisation 
statistics:
sklearn(scikit learn):machine learning
keras:deep learning
tensorflow:google
pytorch:facebook

In [2]:
#pandas is used for data manipulation and we can craete series data and datafarames data using pandas

series:-contains 1d data
dataframe:-contains 2D data

SyntaxError: invalid decimal literal (3542314188.py, line 3)

In [2]:
import pandas as pd
pd.Series([1,3,5,6,7])

0    1
1    3
2    5
3    6
4    7
dtype: int64

In [3]:
#3 emp id name email salerty
dict1={"id":[111,112,113],"name":['s','p','k'],"email":['a1@gmail.com','b1@gmail.com','a1@gmail.com'],"salery":['10000','100','4500']}
dict1

{'id': [111, 112, 113],
 'name': ['s', 'p', 'k'],
 'email': ['a1@gmail.com', 'b1@gmail.com', 'a1@gmail.com'],
 'salery': ['10000', '100', '4500']}

In [4]:
pd.DataFrame(dict1)

    id name         email salery
0  111    s  a1@gmail.com  10000
1  112    p  b1@gmail.com    100
2  113    k  a1@gmail.com   4500

In [5]:

d1=pd.read_excel("C:\\Users\\ar543\\Downloads\\emp_data.xlsx")
d1

   eid ename   sal  dept
0    1    aa  1234    10
1    2    bb  2345    20
2    3    cc  3214    30
3    4    dd  5332    40

In [6]:
d2=pd.read_csv("C:\\Users\\ar543\\Downloads\\studata.txt")
d2

   sid    sname            emialid address  phoneno
0    1    priya    priya@gmail.com     dvg     9876
1    2  karthik  karthik@gmail.com     blr    12345
2    3    karan                NaN     msr    34567

In [7]:
d3=pd.read_csv("C:\\Users\\ar543\\Downloads\\mtcars.csv")
d3

,manufacturer,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
5,Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1
6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
10,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4
11,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3
12,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3
13,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3
14,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
15,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4
16,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
17,Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1
18,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
19,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
20,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1
21,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2
22,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2
23,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
24,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2
25,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1
26,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2

In [8]:
d4=pd.read_table("C:\\Users\\ar543\\Downloads\\chipotle.tsv")
d4

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

In [9]:
d5=pd.read_csv("C:\\Users\\ar543\\Downloads\\chipotle.tsv",sep="\t")
d5

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

In [10]:
d5.head(5)

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98

In [11]:
d5.tail(10)

,order_id,quantity,item_name,choice_description,item_price
4612,1831,1,Carnitas Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$9.25
4613,1831,1,Chips,NaN,$2.15
4614,1831,1,Bottled Water,NaN,$1.50
4615,1832,1,Chicken Soft Tacos,"[Fresh Tomato Salsa, [Rice, Cheese, Sour Cream]]",$8.75
4616,1832,1,Chips and Guacamole,NaN,$4.45
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

In [12]:
#make data with 500 rows
temp=d5.sample(500,)
temp

,order_id,quantity,item_name,choice_description,item_price
4330,1728,1,Chips,NaN,$2.15
550,230,1,Chips and Guacamole,NaN,$4.45
1792,724,1,Canned Soft Drink,[Coke],$1.25
1165,480,1,Canned Soft Drink,[Diet Coke],$1.25
1177,484,2,Bottled Water,NaN,$2.18
...,...,...,...,...,...
4121,1651,1,Chicken Bowl,"[Tomatillo Red Chili Salsa, [Rice, Cheese, Let...",$8.75
3033,1206,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Cheese, Lettuce]]",$8.75
1728,697,1,Chicken Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",$11.25
4228,1688,1,Steak Bowl,"[Tomatillo Green Chili Salsa, [Rice, Pinto Bea...",$11.75
3500,1405,1,Side of Chips,NaN,$1.69

In [13]:
d5.shape

(4622, 5)

In [14]:
#how to extract only rows
d5.shape[1]

5

In [15]:
#columns names
d5.columns

Index(['order_id', 'quantity', 'item_name', 'choice_description',
       'item_price'],
      dtype='object')

In [16]:
d5.dtypes

order_id               int64
quantity               int64
item_name             object
choice_description    object
item_price            object
dtype: object

In [17]:
d3.manufacturer

0               Mazda RX4
1           Mazda RX4 Wag
2              Datsun 710
3          Hornet 4 Drive
4       Hornet Sportabout
5                 Valiant
6              Duster 360
7               Merc 240D
8                Merc 230
9                Merc 280
10              Merc 280C
11             Merc 450SE
12             Merc 450SL
13            Merc 450SLC
14     Cadillac Fleetwood
15    Lincoln Continental
16      Chrysler Imperial
17               Fiat 128
18            Honda Civic
19         Toyota Corolla
20          Toyota Corona
21       Dodge Challenger
22            AMC Javelin
23             Camaro Z28
24       Pontiac Firebird
25              Fiat X1-9
26          Porsche 914-2
27           Lotus Europa
28         Ford Pantera L
29           Ferrari Dino
30          Maserati Bora
31             Volvo 142E
Name: manufacturer, dtype: object

In [18]:
d3=pd.read_csv("C:\\Users\\ar543\\Downloads\\mtcars.csv")

In [19]:
d3

,manufacturer,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
5,Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1
6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
10,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4
11,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3
12,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3
13,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3
14,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
15,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4
16,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
17,Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1
18,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
19,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
20,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1
21,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2
22,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2
23,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
24,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2
25,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1
26,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2

In [21]:
d3.manufacturer

0               Mazda RX4
1           Mazda RX4 Wag
2              Datsun 710
3          Hornet 4 Drive
4       Hornet Sportabout
5                 Valiant
6              Duster 360
7               Merc 240D
8                Merc 230
9                Merc 280
10              Merc 280C
11             Merc 450SE
12             Merc 450SL
13            Merc 450SLC
14     Cadillac Fleetwood
15    Lincoln Continental
16      Chrysler Imperial
17               Fiat 128
18            Honda Civic
19         Toyota Corolla
20          Toyota Corona
21       Dodge Challenger
22            AMC Javelin
23             Camaro Z28
24       Pontiac Firebird
25              Fiat X1-9
26          Porsche 914-2
27           Lotus Europa
28         Ford Pantera L
29           Ferrari Dino
30          Maserati Bora
31             Volvo 142E
Name: manufacturer, dtype: object

In [22]:
d3['manufacturer']

0               Mazda RX4
1           Mazda RX4 Wag
2              Datsun 710
3          Hornet 4 Drive
4       Hornet Sportabout
5                 Valiant
6              Duster 360
7               Merc 240D
8                Merc 230
9                Merc 280
10              Merc 280C
11             Merc 450SE
12             Merc 450SL
13            Merc 450SLC
14     Cadillac Fleetwood
15    Lincoln Continental
16      Chrysler Imperial
17               Fiat 128
18            Honda Civic
19         Toyota Corolla
20          Toyota Corona
21       Dodge Challenger
22            AMC Javelin
23             Camaro Z28
24       Pontiac Firebird
25              Fiat X1-9
26          Porsche 914-2
27           Lotus Europa
28         Ford Pantera L
29           Ferrari Dino
30          Maserati Bora
31             Volvo 142E
Name: manufacturer, dtype: object

In [23]:
d3[['manufacturer']]

           manufacturer
0             Mazda RX4
1         Mazda RX4 Wag
2            Datsun 710
3        Hornet 4 Drive
4     Hornet Sportabout
5               Valiant
6            Duster 360
7             Merc 240D
8              Merc 230
9              Merc 280
10            Merc 280C
11           Merc 450SE
12           Merc 450SL
13          Merc 450SLC
14   Cadillac Fleetwood
15  Lincoln Continental
16    Chrysler Imperial
17             Fiat 128
18          Honda Civic
19       Toyota Corolla
20        Toyota Corona
21     Dodge Challenger
22          AMC Javelin
23           Camaro Z28
24     Pontiac Firebird
25            Fiat X1-9
26        Porsche 914-2
27         Lotus Europa
28       Ford Pantera L
29         Ferrari Dino
30        Maserati Bora
31           Volvo 142E

In [26]:
temp1=d3[['mpg','wt','vs','am']]
temp1

     mpg     wt  vs  am
0   21.0  2.620   0   1
1   21.0  2.875   0   1
2   22.8  2.320   1   1
3   21.4  3.215   1   0
4   18.7  3.440   0   0
5   18.1  3.460   1   0
6   14.3  3.570   0   0
7   24.4  3.190   1   0
8   22.8  3.150   1   0
9   19.2  3.440   1   0
10  17.8  3.440   1   0
11  16.4  4.070   0   0
12  17.3  3.730   0   0
13  15.2  3.780   0   0
14  10.4  5.250   0   0
15  10.4  5.424   0   0
16  14.7  5.345   0   0
17  32.4  2.200   1   1
18  30.4  1.615   1   1
19  33.9  1.835   1   1
20  21.5  2.465   1   0
21  15.5  3.520   0   0
22  15.2  3.435   0   0
23  13.3  3.840   0   0
24  19.2  3.845   0   0
25  27.3  1.935   1   1
26  26.0  2.140   0   1
27  30.4  1.513   1   1
28  15.8  3.170   0   1
29  19.7  2.770   0   1
30  15.0  3.570   0   1
31  21.4  2.780   1   1

In [ ]:
rename column wt by weight and manufacturer as menu

In [34]:
d3.rename({"wt":"weight","manufacturer":"manu"},errors="raise",axis=1,inplace=True)

KeyError: "['wt', 'manufacturer'] not found in axis"

In [35]:
d3

,manu,mpg,cyl,disp,hp,drat,weight,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
5,Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1
6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
10,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4
11,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3
12,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3
13,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3
14,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
15,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4
16,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
17,Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1
18,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
19,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
20,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1
21,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2
22,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2
23,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
24,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2
25,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1
26,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2

In [44]:
#count how many unique values are in cyl column

d3['cyl'].nunique()

3

In [42]:
d3['cyl'].unique()

array([6, 4, 8])

In [45]:
d3.nunique()

manu      32
mpg       25
cyl        3
disp      27
hp        22
drat      22
weight    29
qsec      30
vs         2
am         2
gear       3
carb       6
dtype: int64

In [46]:
!git add .

warning: in the working copy of 'exception handling.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of '.ipynb_checkpoints/Untitled1-checkpoint.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of '.ipynb_checkpoints/libraries-checkpoint.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'Untitled1.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'libraries.ipynb', LF will be replaced by CRLF the next time Git touches it

In [47]:
!git commit -m "pandas libraries"

[main cc01bad] pandas libraries
 5 files changed, 4064 insertions(+), 6 deletions(-)
 create mode 100644 .ipynb_checkpoints/Untitled1-checkpoint.ipynb
 create mode 100644 .ipynb_checkpoints/libraries-checkpoint.ipynb
 create mode 100644 Untitled1.ipynb
 create mode 100644 libraries.ipynb

In [48]:
!git push

To https://github.com/aryanra419/Python-class-notes
   4bcdd73..cc01bad  main -> main

In [53]:
#create half qsec
d3["Half qsec"] = d3["qsec"]/2

In [54]:
d3

,manu,mpg,cyl,disp,hp,drat,weight,qsec,vs,am,gear,carb,Half qsec
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4,8.230
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4,8.510
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1,9.305
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1,9.720
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2,8.510
5,Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1,10.110
6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4,7.920
7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2,10.000
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2,11.450
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4,9.150
10,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4,9.450
11,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3,8.700
12,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3,8.800
13,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3,9.000
14,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4,8.990
15,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4,8.910
16,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4,8.710
17,Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1,9.735
18,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2,9.260
19,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1,9.950
20,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1,10.005
21,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2,8.435
22,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2,8.650
23,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4,7.705
24,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2,8.525
25,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1,9.450
26,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2,8.350
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2,8.450
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4,7.250
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6,7.750
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8,7.300
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2,9.300

In [64]:
d3["Car type"] = d3["am"]==1

In [58]:
d3

,manu,mpg,cyl,disp,hp,drat,weight,qsec,vs,am,gear,carb,Half qsec,Car type
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4,8.230,True
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4,8.510,True
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1,9.305,True
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1,9.720,False
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2,8.510,False
5,Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1,10.110,False
6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4,7.920,False
7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2,10.000,False
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2,11.450,False
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4,9.150,False
10,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4,9.450,False
11,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3,8.700,False
12,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3,8.800,False
13,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3,9.000,False
14,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4,8.990,False
15,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4,8.910,False
16,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4,8.710,False
17,Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1,9.735,True
18,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2,9.260,True
19,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1,9.950,True
20,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1,10.005,False
21,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2,8.435,False
22,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2,8.650,False
23,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4,7.705,False
24,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2,8.525,False
25,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1,9.450,True
26,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2,8.350,True
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2,8.450,True
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4,7.250,True
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6,7.750,True
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8,7.300,True
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2,9.300,True